In [5]:
import numpy as np
a = np.array([[20,30],[40,10]])
print(np.append(a,[80,75]))

[20 30 40 10 80 75]


In [7]:
a = np.array([10,20,30,40])   
print(np.insert(a,1,50))    #[arr,index,value]

[10 50 20 30 40]


In [8]:
a =np.array([[10,20],[30,40],[50,72]])
print(np.insert(a,1,99))

[10 99 20 30 40 50 72]


In [15]:
a =np.array([[10,20],[30,40],[50,72]])
print(np.delete(a,1,axis=0))

[[10 20]
 [50 72]]
