In [1]:
#concatenate
import numpy as np

arr1 = np.array([10,20,30,40])
arr2 = np.array([5,4,3,2,])
print(np.concatenate([arr1,arr2]))

[10 20 30 40  5  4  3  2]


In [2]:
print(np.concatenate([arr1,arr2],axis = 0))

[10 20 30 40  5  4  3  2]


In [3]:
print(np.hstack([arr1,arr2]))   #horizantal concatenation == axis=1

[10 20 30 40  5  4  3  2]


In [4]:
print(np.vstack([arr1,arr2]))   #vertical concatenation

[[10 20 30 40]
 [ 5  4  3  2]]


In [14]:
a =np.array([[10,20],[30,40],[50,60]])
b=np.array_split(a,2)
print(b)

[array([[10, 20],
       [30, 40]]), array([[50, 60]])]
